# Generated by Django 4.1 on 2022-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.UUIDField()),
                ('book_name', models.TextField()),
                ('book_small_desc', models.TextField()),
                ('book_desc', models.TextField()),
                ('book_image', models.TextField()),
                ('book_review_star', models.PositiveSmallIntegerField()),
                ('book_author', models.CharField(max_length=60)),
                ('book_published', models.CharField(max_length=60)),
            ],
        ),
    ]
