# Generated by Django 4.1 on 2022-09-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='book_id',
        ),
    ]
