# Generated by Django 4.1 on 2022-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bookdata_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.PositiveSmallIntegerField()),
                ('user_email', models.TextField(max_length=60)),
            ],
        ),
    ]
