# Generated by Django 4.1 on 2022-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reviewdata_bookdata_book_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='username',
            field=models.TextField(default='No User', max_length=60),
        ),
    ]
