# Generated by Django 4.1 on 2022-09-20 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reviewdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
